# 13(f) securities pipeline

Builds the CUSIP reference tables from the SEC *Official List of Section 13(f) Securities*:
quarterly CSV files → `input_1.f13_securities` (one row per list entry) → `clean_up_1.asset` (one row per CUSIP). Every block shows the database feedback
(status message, affected rows, duration, result set) and is written to the run log
`logs/f13_securities/<RUN_ID>/`, so runs can be compared later (section 6). Execution and logging code lives
in `src/pipeline_helpers.py`.

The CSV files come from `Database/13f_securities` (`main.py`): SEC PDF lists → text extraction (2004+) or
OCR (1996–2003, issues in `data/ocr_issues.tsv`) → fixed-width TXT → `data/csv/13flistYYYYqN.csv`,
1996 Q1 – 2020 Q4.

| Section | Phase label | What happens |
|---|---|---|
| 0.2 Database connection | `connection` | read-only check, then working connection |
| 1. Securities table | `securities_create` | `f13_securities_setup.sql`, CUSIP check-digit function |
| 2. Load CSV files | `securities_load` | one transaction per file (replaces `load_13f_securities.py`) |
| 3. Securities profile | `securities_profile` | totals, rows per year, duplicates, invalid check digits |
| 4. Build asset table | `asset_build` | one row per valid CUSIP with first / last quarter |
| 5. Asset checks | `asset_checks` | counts, gaps in listing |

> **The cells modify the database.** `clean_up_1.asset` is dropped and rebuilt in section 4.

## 0. Setup

### 0.1 Configuration

* `CSV_DIR`: the quarterly list files
* `RECREATE_SECURITIES`: `True` drops and recreates the securities table before the load. Not needed for a
  normal re-run: the loader replaces each file's rows.

In [1]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd().parent                       # .../Database/Initialisation (notebooks run from notebooks/)
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "config")]

from pipeline_helpers import (F13ListLoader, PipelineRun, compare_runs, expected_mismatches,
                              load_logs, phase_durations, steps_table)
from local_config import DSN   # machine-specific, git-ignored (template: local_config.example.py)

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)

LOG_ROOT = ROOT / "logs" / "f13_securities"

SECURITIES_TABLE = "input_1.f13_securities"
ASSET_TABLE      = "clean_up_1.asset"

# Output of Database/13f_securities (SEC PDF lists -> TXT -> CSV)
CSV_DIR = ROOT.parent / "13f_securities" / "data" / "csv"

RECREATE_SECURITIES = True   # True = drop and recreate the securities table before the load

# The tables are small (<1M rows), so exact count(*) is cheap
p = PipelineRun(LOG_ROOT, dsn=DSN, max_rows=1000, exact_counts=True)
print("RUN_ID :", p.run_id)
print("LOG_DIR:", p.log_dir)

RUN_ID : 20261011_201543
LOG_DIR: <THESIS_DIR>/src/Clean_solution/Database/Initialisation/pipelines/logs/f13_securities/20261011_201543

### 0.2 Database connection

First a read-only check on a separate connection (`READ ONLY` transaction, rolled back): server, database,
user, schema privileges, current state of both tables. The working connection (autocommit) is opened only if
the check passes.

In [2]:
CONNECTION_OK = p.check_connection(DSN, schemas=["input_1", "clean_up_1"],
                                   tables=[SECURITIES_TABLE, ASSET_TABLE])

✅ **[connection] connection_check_server**: `ok` | 0.0s

> READ ONLY transaction, rolled back. Nothing committed.

                                      server_version     database   db_user  is_standby txn_read_only db_size  other_sessions
0  PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04....  Holdings_v2  postgres       False            on   53 GB               2

✅ **[connection] connection_check_schemas**: `ok`

  schema_name  schema_exists  can_create  can_use
0     input_1           True        True     True
1  clean_up_1           True        True     True

✅ **[connection] connection_check_tables**: `ok`

> Existing tables will be dropped and recreated by the pipeline.

               table_name  exists  unlogged  est_rows total_size
0  input_1.f13_securities    True     False    856547     123 MB
1        clean_up_1.asset    True     False     67216      39 MB

In [3]:
assert CONNECTION_OK, "Connection check failed, see connection_check_server above"
p.connect()

Connected: user=postgres password=xxx dbname=Holdings_v2 host=localhost port=5432

## 1. Securities table

`input_1.f13_securities` holds one row per list entry (`f13_securities_setup.sql`). There is no unique key on
(`cusip`, `year`, `quarter`): some OCR'd lists contain the same CUSIP twice.

`input_1.cusip_check_digit(c8)` computes the 9th CUSIP character from the first 8 (same function as in the holdings pipeline). A listed CUSIP whose 9th character differs was misread by the OCR (section 3).

In [4]:
sec = p.stage("securities_create")

if RECREATE_SECURITIES:
    sec.run("drop_securities_table", f"DROP TABLE IF EXISTS {SECURITIES_TABLE};")

sec.run("create_securities_table", f"""
    CREATE TABLE IF NOT EXISTS {SECURITIES_TABLE} (
        id                 BIGSERIAL PRIMARY KEY,
        year               SMALLINT    NOT NULL,
        quarter            SMALLINT    NOT NULL CHECK (quarter BETWEEN 1 AND 4),
        cusip              VARCHAR(9)  NOT NULL,
        has_option         BOOLEAN,
        issuer_name        TEXT,
        issuer_description TEXT,
        status             CHAR(1),
        flag               CHAR(1),
        source_file        TEXT        NOT NULL
    );
""")

✅ **[securities_create] drop_securities_table**: `ok` | `DROP TABLE` | 0.0s

✅ **[securities_create] create_securities_table**: `ok` | `CREATE TABLE` | 0.0s

Empty DataFrame
Columns: []
Index: []

In [5]:
sec.run("idx_securities_cusip", f"""
    CREATE INDEX IF NOT EXISTS f13_securities_cusip_idx ON {SECURITIES_TABLE} (cusip);
""")
sec.run("idx_securities_year_quarter", f"""
    CREATE INDEX IF NOT EXISTS f13_securities_year_quarter_idx ON {SECURITIES_TABLE} (year, quarter);
""")

✅ **[securities_create] idx_securities_cusip**: `ok` | `CREATE INDEX` | 0.0s

✅ **[securities_create] idx_securities_year_quarter**: `ok` | `CREATE INDEX` | 0.0s

Empty DataFrame
Columns: []
Index: []

In [6]:
sec.run("create_cusip_check_digit", r"""
    -- CUSIP check digit (9th character) computed from cusip8.
    -- Returns NULL if cusip8 is NULL or not 8 valid characters.
    CREATE OR REPLACE FUNCTION input_1.cusip_check_digit(c8 text)
    RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
      SELECT CASE WHEN c8 ~ '^[0-9A-Za-z*@#]{8}$' THEN
        ((10 - sum(v / 10 + v % 10) % 10) % 10)::text
      END
      FROM (
        SELECT CASE WHEN i % 2 = 0 THEN 2 * val ELSE val END AS v   -- even (1-based) positions doubled
        FROM (
          SELECT i,
                 CASE WHEN ch ~ '[0-9]'    THEN ch::int
                      WHEN ch ~ '[A-Za-z]' THEN ascii(upper(ch)) - 55   -- A=10 ... Z=35
                      WHEN ch = '*' THEN 36
                      WHEN ch = '@' THEN 37
                      ELSE 38 END AS val                                -- '#'
          FROM (SELECT i, substr(c8, i, 1) AS ch FROM generate_series(1, 8) i) s
        ) t
      ) d
    $$;
""")

# Sanity check: Apple 037833100 -> check digit '0'
chk_digit = sec.run("check_digit_sanity", "SELECT input_1.cusip_check_digit('03783310') AS digit;")
assert chk_digit.iloc[0, 0] == "0", "cusip_check_digit is wrong"

✅ **[securities_create] create_cusip_check_digit**: `ok` | `CREATE FUNCTION` | 0.0s

✅ **[securities_create] check_digit_sanity**: `ok` | `SELECT 1` | rows: **1** | 0.0s

  digit
0     0

## 2. Load the CSV files

Same rules as `f13_securities/load_13f_securities.py`:
* `year` / `quarter` from the file name (`13flist1997q1.csv` → 1997, 1)
* `has_option` `Y` / `N` → boolean, blank fields → `NULL`, rows without a CUSIP are skipped
* each file is loaded in its own transaction and **replaces** that file's previous rows, so re-running is safe
* files are read as Latin-1; the header must be `cusip,has_option,issuer_name,issuer_description,status,flag`

The preflight lists the files and the missing quarters (1997 Q4 has no list).

In [7]:
loader = F13ListLoader(p.stage("securities_load"), CSV_DIR, SECURITIES_TABLE)

loader.preflight()

✅ **[securities_load] preflight_csv_files**: `ok` | rows: **99**

> <PROJECTS_DIR>/Sec_data_gathering/13f_lists_pre2021/csv  |  missing quarters: 1997q4

                 file  year  quarter   kb
0   13flist1996q1.csv  1996        1  429
1   13flist1996q2.csv  1996        2  433
2   13flist1996q3.csv  1996        3  438
3   13flist1996q4.csv  1996        4  446
4   13flist1997q1.csv  1997        1  448
..                ...   ...      ...  ...
94  13flist2019q4.csv  2019        4  385
95  13flist2020q1.csv  2020        1  395
96  13flist2020q2.csv  2020        2  400
97  13flist2020q3.csv  2020        3  408
98  13flist2020q4.csv  2020        4  432

[99 rows x 4 columns]

True

In [8]:
loaded = loader.run()   # previous run: 99 files, 856,547 rows

✅ **[securities_load] load_csv_files**: `ok` | rows: **856,547** | 7.4s

> 99 files | skipped rows without CUSIP: 0

                 file  year  quarter  in_csv  replaced  inserted  seconds error
0   13flist1996q1.csv  1996        1   10480         0     10480     0.05  None
1   13flist1996q2.csv  1996        2   10654         0     10654     0.05  None
2   13flist1996q3.csv  1996        3   10796         0     10796     0.05  None
3   13flist1996q4.csv  1996        4   10992         0     10992     0.05  None
4   13flist1997q1.csv  1997        1   11046         0     11046     0.05  None
..                ...   ...      ...     ...       ...       ...      ...   ...
94  13flist2019q4.csv  2019        4    8866         0      8866     0.09  None
95  13flist2020q1.csv  2020        1    8880         0      8880     0.09  None
96  13flist2020q2.csv  2020        2    8972         0      8972     0.14  None
97  13flist2020q3.csv  2020        3    9134         0      9134     0.09  None
98  13flist2020q4.csv  2020        4    9598         0      9598     0.10  None

[99 rows x 8 columns]

## 3. Securities profile

In [9]:
prof = p.stage("securities_profile")

prof.row_estimate(SECURITIES_TABLE, "securities")
prof.run("securities_totals", f"""
    SELECT count(*)                                          AS total,
           count(DISTINCT source_file)                       AS files,
           count(DISTINCT cusip)                             AS distinct_cusip,
           count(*) FILTER (WHERE length(cusip) <> 9)        AS cusip_not9,
           count(*) FILTER (WHERE has_option)                AS has_option,
           count(*) FILTER (WHERE has_option IS NULL)        AS has_option_null,
           count(*) - count(DISTINCT (cusip, year, quarter)) AS duplicate_in_quarter,
           count(*) FILTER (WHERE status = 'A')              AS status_added,
           count(*) FILTER (WHERE status = 'D')              AS status_deleted
    FROM {SECURITIES_TABLE};
""", note="Previous run: total 856,547 | files 99 | distinct_cusip 42,094 | cusip_not9 0 | "
          "has_option 362,283 | duplicate_in_quarter 399 | status A 30,121 | status D 30,585")

✅ **[securities_profile] securities_count_exact**: `ok` | `SELECT 1` | rows: **1** | 0.0s

        n
0  856547

✅ **[securities_profile] securities_totals**: `ok` | `SELECT 1` | rows: **1** | 2.0s

> Previous run: total 856,547 | files 99 | distinct_cusip 42,094 | cusip_not9 0 | has_option 362,283 | duplicate_in_quarter 399 | status A 30,121 | status D 30,585

    total  files  distinct_cusip  cusip_not9  has_option  has_option_null  duplicate_in_quarter  status_added  status_deleted
0  856547     99           42094           0      362283                0                   399         30121           30585

    total  files  distinct_cusip  cusip_not9  has_option  has_option_null  duplicate_in_quarter  status_added  status_deleted
0  856547     99           42094           0      362283                0                   399         30121           30585

In [10]:
prof.run("securities_per_year", f"""
    SELECT year,
           count(DISTINCT quarter)            AS quarters,
           count(*)                           AS rows,
           round(count(*)::numeric / count(DISTINCT quarter)) AS rows_per_quarter,
           count(*) FILTER (WHERE has_option) AS has_option
    FROM {SECURITIES_TABLE}
    GROUP BY year
    ORDER BY year;
""")

✅ **[securities_profile] securities_per_year**: `ok` | `SELECT 25` | rows: **25** | 0.1s

    year  quarters   rows rows_per_quarter  has_option
0   1996         4  42922            10731        8730
1   1997         3  33125            11042        7244
2   1998         4  43601            10900       11681
3   1999         4  40646            10162       11620
4   2000         4  39242             9811       11661
5   2001         4  36408             9102       11965
6   2002         4  33765             8441       12488
7   2003         4  31710             7928       11707
8   2004         4  31594             7899       11697
9   2005         4  31965             7991       12396
10  2006         4  31832             7958       13033
11  2007         4  32898             8225       14081
12  2008         4  33100             8275       14684
13  2009         4  31248             7812       14966
14  2010         4  30950             7738       15445
15  2011         4  31199             7800       16179
16  2012         4  31147             7787       16532
17  2013         4  30790             7698       17204
18  2014         4  31871             7968       17934
19  2015         4  33092             8273       18566
20  2016         4  33478             8370       18896
21  2017         4  33806             8452       18482
22  2018         4  34614             8654       18556
23  2019         4  34960             8740       18188
24  2020         4  36584             9146       18348

    year  quarters   rows rows_per_quarter  has_option
0   1996         4  42922            10731        8730
1   1997         3  33125            11042        7244
2   1998         4  43601            10900       11681
3   1999         4  40646            10162       11620
4   2000         4  39242             9811       11661
5   2001         4  36408             9102       11965
6   2002         4  33765             8441       12488
7   2003         4  31710             7928       11707
8   2004         4  31594             7899       11697
9   2005         4  31965             7991       12396
10  2006         4  31832             7958       13033
11  2007         4  32898             8225       14081
12  2008         4  33100             8275       14684
13  2009         4  31248             7812       14966
14  2010         4  30950             7738       15445
15  2011         4  31199             7800       16179
16  2012         4  31147             7787       16532
17  2013         4  30790             7698       17204
18  2014         4  31871             7968       17934
19  2015         4  33092             8273       18566
20  2016         4  33478             8370       18896
21  2017         4  33806             8452       18482
22  2018         4  34614             8654       18556
23  2019         4  34960             8740       18188
24  2020         4  36584             9146       18348

In [11]:
prof.run("securities_duplicates", f"""
    -- same CUSIP listed more than once in a quarter (OCR); only one is kept in the CUSIP table
    SELECT cusip, year, quarter, count(*) AS times,
           string_agg(DISTINCT coalesce(issuer_name, '(null)'), ' | ') AS issuer_names
    FROM {SECURITIES_TABLE}
    GROUP BY cusip, year, quarter
    HAVING count(*) > 1
    ORDER BY times DESC, year, quarter
    LIMIT 50;
""")

✅ **[securities_profile] securities_duplicates**: `ok` | `SELECT 50` | rows: **50** | 0.8s

        cusip  year  quarter  times                                       issuer_names
0   628546103  1996        1      3                                         MYLEX CORP
1   200300101  1996        1      3       COMCAST CORP | COMCAST CORP                C
2   451841100  1996        1      3                                 ILLINOIS CENT CORP
3   895927101  1996        1      3  TRIARC COS INC              C | TRIARC COS INC...
4   814208104  1997        2      3                      SECURITY DYNAMICS TECHNOLOGIE
5   257661504  1999        2      3                     DONALDSON LUFKIN & JENRETTE  N
6   872879101  1999        2      3                     TSI INTERNATIONAL S OFTWARE LT
7   743168106  1999        2      3                     PROFIT RECOVERY GROUP INTL  IN
8   371931106  1999        2      3                     GENESYS TELE COMMUNICATION LAB
9   130209604  1999        2      3                      CALIFORNIA FED BK FSB LOS ANG
10  300906104  1999        2      3                     EXCELSIOR HENDERSON MOTORCY CL
11  B5628B104  1999        2      3                     LERNOUT & HAUSPIE SPE ECH PROD
12  222814204  1999        2      3                      COVAD COMMUNICATIONS GROUP IN
13  111021408  1999        2      3                      BRITISH TELECOMMUNICATIONS PL
14  203902101  1999        2      3                      COMMUNITY FIRST BANKSHARES IN
15  45669P101  1999        2      3                     INFORMATION ADVANTAGE  SOFTWAR
16  204925101  1999        2      3  COMPUTER NETWORK TECHNOLOGY C | COMPUTER NETWO...
17  257661108  1999        2      3                      DONALDSON LUFKIN & JENRETTE N
18  358433100  1999        2      3                     FRIEDMAN BILLINGS RAMSEY GRO U
19  168905107  2000        1      3                     CHILDRENS PL RETAIL ST ORES IN
20  397888108  2002        4      3                                      GREY WOLF INC
21  04649A106  2003        1      3                             AT & T LATIN AMER CORP
22  205937105  2003        1      3                                          COM21 INC
23  253756100  2003        1      3                                      DIGEX INC DEL
24  904763208  2003        1      3                                    UNILAB CORP NEW
25  278751102  2003        1      3                                 ECHO BAY MINES LTD
26  847608106  2003        1      3                                     SPECTRIAN CORP
27  705904100  2003        1      3                        PEGASUS COMMUNICATIONS CORP
28  252826102  2003        1      3                                     DIANON SYS INC
29  716597109  2003        1      3                             PETROLEUM GEO-SVCS A/S
30  551812308  2003        1      3                              LYNX THERAPEUTICS INC
31  496902206  2003        1      3                                  KINROSS GOLD CORP
32  530129105  2003        1      3                              LIBERATE TECHNOLOGIES
33  030411102  2003        1      3                               AMERICAN WTR WKS INC
34  496902107  2003        1      3                                  KINROSS GOLD CORP
35  63935M109  2003        1      3                                       NAVISITE INC
36  860831106  2003        1      3                                  STILWELL FINL INC
37  232565101  2003        1      3                                        CYLINK CORP
38  749388104  2003        2      3                                           RC2 CORP
39  227483104  2003        2      3                          CROSS CTRY HEALTHCARE INC
40  137694105  1996        1      2                                 CANNON EXPRESS INC
41  02608W101  1996        1      2  AMERICAN FINL GROUP INC | AMERICAN FINL GROUP ...
42  356714402  1996        1      2  FREEPORT MCMORAN INC | FREEPORT MCMORAN INC   ...
43  050103100  1996        1      2   AU BON PAIN INC | AU BON PAIN INC              P
44  379355100  1996        1      2  GLOBAL NAT RES INC | GLOBAL NAT RES INC       ...
45  128787108  1996        1      2                       CALDGR CORP  . | CALDOR CORP
46  022615108  1996        1      2     ALZA CORP DEL | ALZA CORP DEL                C
47  281760108  1996        1      2    EDWARDS AG INC | EDWARD  S AG INC             P
48  124883208  1996        1      2                                            CCH INC
49  039665104  1996        1      2        ARCTCO INC | ARCTCO INC                   C

        cusip  year  quarter  times                                       issuer_names
0   628546103  1996        1      3                                         MYLEX CORP
1   200300101  1996        1      3       COMCAST CORP | COMCAST CORP                C
2   451841100  1996        1      3                                 ILLINOIS CENT CORP
3   895927101  1996        1      3  TRIARC COS INC              C | TRIARC COS INC...
4   814208104  1997        2      3                      SECURITY DYNAMICS TECHNOLOGIE
5   257661504  1999        2      3                     DONALDSON LUFKIN & JENRETTE  N
6   872879101  1999        2      3                     TSI INTERNATIONAL S OFTWARE LT
7   743168106  1999        2      3                     PROFIT RECOVERY GROUP INTL  IN
8   371931106  1999        2      3                     GENESYS TELE COMMUNICATION LAB
9   130209604  1999        2      3                      CALIFORNIA FED BK FSB LOS ANG
10  300906104  1999        2      3                     EXCELSIOR HENDERSON MOTORCY CL
11  B5628B104  1999        2      3                     LERNOUT & HAUSPIE SPE ECH PROD
12  222814204  1999        2      3                      COVAD COMMUNICATIONS GROUP IN
13  111021408  1999        2      3                      BRITISH TELECOMMUNICATIONS PL
14  203902101  1999        2      3                      COMMUNITY FIRST BANKSHARES IN
15  45669P101  1999        2      3                     INFORMATION ADVANTAGE  SOFTWAR
16  204925101  1999        2      3  COMPUTER NETWORK TECHNOLOGY C | COMPUTER NETWO...
17  257661108  1999        2      3                      DONALDSON LUFKIN & JENRETTE N
18  358433100  1999        2      3                     FRIEDMAN BILLINGS RAMSEY GRO U
19  168905107  2000        1      3                     CHILDRENS PL RETAIL ST ORES IN
20  397888108  2002        4      3                                      GREY WOLF INC
21  04649A106  2003        1      3                             AT & T LATIN AMER CORP
22  205937105  2003        1      3                                          COM21 INC
23  253756100  2003        1      3                                      DIGEX INC DEL
24  904763208  2003        1      3                                    UNILAB CORP NEW
25  278751102  2003        1      3                                 ECHO BAY MINES LTD
26  847608106  2003        1      3                                     SPECTRIAN CORP
27  705904100  2003        1      3                        PEGASUS COMMUNICATIONS CORP
28  252826102  2003        1      3                                     DIANON SYS INC
29  716597109  2003        1      3                             PETROLEUM GEO-SVCS A/S
30  551812308  2003        1      3                              LYNX THERAPEUTICS INC
31  496902206  2003        1      3                                  KINROSS GOLD CORP
32  530129105  2003        1      3                              LIBERATE TECHNOLOGIES
33  030411102  2003        1      3                               AMERICAN WTR WKS INC
34  496902107  2003        1      3                                  KINROSS GOLD CORP
35  63935M109  2003        1      3                                       NAVISITE INC
36  860831106  2003        1      3                                  STILWELL FINL INC
37  232565101  2003        1      3                                        CYLINK CORP
38  749388104  2003        2      3                                           RC2 CORP
39  227483104  2003        2      3                          CROSS CTRY HEALTHCARE INC
40  137694105  1996        1      2                                 CANNON EXPRESS INC
41  02608W101  1996        1      2  AMERICAN FINL GROUP INC | AMERICAN FINL GROUP ...
42  356714402  1996        1      2  FREEPORT MCMORAN INC | FREEPORT MCMORAN INC   ...
43  050103100  1996        1      2   AU BON PAIN INC | AU BON PAIN INC              P
44  379355100  1996        1      2  GLOBAL NAT RES INC | GLOBAL NAT RES INC       ...
45  128787108  1996        1      2                       CALDGR CORP  . | CALDOR CORP
46  022615108  1996        1      2     ALZA CORP DEL | ALZA CORP DEL                C
47  281760108  1996        1      2    EDWARDS AG INC | EDWARD  S AG INC             P
48  124883208  1996        1      2                                            CCH INC
49  039665104  1996        1      2        ARCTCO INC | ARCTCO INC                   C

### Check digit

`wrong_digit`: the 9th character is not the check digit of the first 8. `bad_characters`: the first 8 contain a
character a CUSIP cannot have (e.g. `?` from the OCR). `valid_twin`: a valid CUSIP with the same first 8
characters exists, so the 9th character was most likely misread. These CUSIPs are left out of the asset table.

In [12]:
prof.run("securities_check_digit", f"""
    WITH c AS (
        SELECT cusip, count(*) AS list_rows,
               input_1.cusip_check_digit(left(cusip, 8)) AS digit
        FROM {SECURITIES_TABLE}
        WHERE length(cusip) = 9
        GROUP BY cusip
    ),
    valid8 AS (SELECT DISTINCT left(cusip, 8) AS c8 FROM c WHERE digit = right(cusip, 1))
    SELECT count(*)                                                        AS distinct_cusips,
           count(*) FILTER (WHERE digit = right(cusip, 1))                 AS valid,
           count(*) FILTER (WHERE digit <> right(cusip, 1))                AS wrong_digit,
           count(*) FILTER (WHERE digit IS NULL)                           AS bad_characters,
           count(*) FILTER (WHERE digit IS DISTINCT FROM right(cusip, 1)
                              AND left(cusip, 8) IN (SELECT c8 FROM valid8)) AS valid_twin,
           sum(list_rows) FILTER (WHERE digit IS DISTINCT FROM right(cusip, 1)) AS invalid_list_rows
    FROM c;
""", note="Previous run: 42,094 CUSIPs | valid 40,324 | wrong_digit 1,593 | bad_characters 177 | "
          "valid_twin 753 | invalid_list_rows 2,164 of 856,547")

✅ **[securities_profile] securities_check_digit**: `ok` | `SELECT 1` | rows: **1** | 0.6s

> Previous run: 42,094 CUSIPs | valid 40,324 | wrong_digit 1,593 | bad_characters 177 | valid_twin 753 | invalid_list_rows 2,164 of 856,547

   distinct_cusips  valid  wrong_digit  bad_characters  valid_twin invalid_list_rows
0            42094  40324         1593             177         753              2164

   distinct_cusips  valid  wrong_digit  bad_characters  valid_twin invalid_list_rows
0            42094  40324         1593             177         753              2164

In [13]:
prof.run("repair_check_digit", f"""
    UPDATE {SECURITIES_TABLE} s
    SET cusip = left(s.cusip, 8) || input_1.cusip_check_digit(left(s.cusip, 8))
    WHERE length(s.cusip) = 9
      AND input_1.cusip_check_digit(left(s.cusip, 8)) IS NOT NULL
      AND input_1.cusip_check_digit(left(s.cusip, 8)) <> right(s.cusip, 1)
      AND right(s.cusip, 1) !~ '[0-9]';
""")

✅ **[securities_profile] repair_check_digit**: `ok` | `UPDATE 1162` | rows: **1,162** | 0.2s

Empty DataFrame
Columns: []
Index: []

## 4. Build the asset table

`clean_up_1.asset` has **one row per CUSIP** instead of one per CUSIP and quarter (`build_cusip.sql` built
`input_1.cusip` that way). A CUSIP does not change: it is listed from its first to its last quarter, so the table keeps:

* `first_year`, `first_quarter`, `last_year`, `last_quarter`: first and last list the CUSIP appears in
* `quarters_listed`: number of lists it appears in
* `quarters_missing`: lists between first and last where it is absent (1997 Q4 has no list and does not
  count). 0 = continuous; see section 5 for the causes of gaps
* `issuer_name`, `issuer_description`: from the latest list the CUSIP appears in (names can change, e.g. after
  a rebranding)

Only CUSIPs with a **valid check digit** are used (section 3); the others are OCR misreads.

No CALL / PUT rows are generated: options have no CUSIP of their own. 13F filings report an option position
under the **underlying's CUSIP** and mark it with `putCall` = `PUT` / `CALL`, so no holding matches a generated
option CUSIP (characters 7–8 = `90` / `95`). Option rows are identified by `putCall` and removed in
`1_holdings_pipeline.ipynb` (2.1). `has_option` stays in `input_1.f13_securities` as listed by the SEC.

In [14]:
build = p.stage("asset_build")

build.run("create_asset_table", f"""
    DROP TABLE IF EXISTS {ASSET_TABLE};

    CREATE TABLE {ASSET_TABLE} (
        cusip              VARCHAR(9)  PRIMARY KEY,
        issuer_name        TEXT,
        issuer_description TEXT,
        first_year         SMALLINT    NOT NULL,
        first_quarter      SMALLINT    NOT NULL CHECK (first_quarter BETWEEN 1 AND 4),
        last_year          SMALLINT    NOT NULL,
        last_quarter       SMALLINT    NOT NULL CHECK (last_quarter BETWEEN 1 AND 4),
        quarters_listed    SMALLINT    NOT NULL,
        quarters_missing   SMALLINT    NOT NULL,
        CHECK ((first_year, first_quarter) <= (last_year, last_quarter))
    );
""")

✅ **[asset_build] create_asset_table**: `ok` | `CREATE TABLE` | 0.0s

Empty DataFrame
Columns: []
Index: []

In [15]:
build.run("insert_underlying", f"""
    INSERT INTO {ASSET_TABLE}
        (cusip, issuer_name, issuer_description,
         first_year, first_quarter, last_year, last_quarter,
         quarters_listed, quarters_missing)
    WITH lists AS (
        -- every quarter that has a list, numbered 1, 2, 3, ... (1997 Q4 has no list)
        SELECT period, row_number() OVER (ORDER BY period) AS list_no
        FROM (SELECT DISTINCT year * 4 + quarter - 1 AS period FROM {SECURITIES_TABLE}) p
    ),
    a AS (
        SELECT cusip,
               min(year * 4 + quarter - 1)          AS first_period,
               max(year * 4 + quarter - 1)          AS last_period,
               count(DISTINCT year * 4 + quarter)   AS quarters_listed,
               -- name / description from the latest list the CUSIP appears in
               (array_agg(issuer_name        ORDER BY year DESC, quarter DESC, issuer_name))[1]        AS issuer_name,
               (array_agg(issuer_description ORDER BY year DESC, quarter DESC, issuer_description))[1] AS issuer_description
        FROM {SECURITIES_TABLE}
        WHERE length(cusip) = 9
          AND input_1.cusip_check_digit(left(cusip, 8)) = right(cusip, 1)   -- valid check digit only
        GROUP BY cusip
    )
    SELECT a.cusip, a.issuer_name, a.issuer_description,
           a.first_period / 4, a.first_period % 4 + 1,
           a.last_period  / 4, a.last_period  % 4 + 1,
           a.quarters_listed,
           (ll.list_no - lf.list_no + 1) - a.quarters_listed
    FROM a
    JOIN lists lf ON lf.period = a.first_period
    JOIN lists ll ON ll.period = a.last_period;
""", expected=40_593, note="one row per distinct CUSIP with a valid check digit (40,593 after the check-digit repair)")

✅ **[asset_build] insert_underlying**: `ok` | `INSERT 0 40593` | rows: **40,593** | expected: 40,593 (diff +0) | 8.5s

> one row per distinct CUSIP with a valid check digit (40,593 after the check-digit repair)

Empty DataFrame
Columns: []
Index: []

In [16]:
build.run("idx_asset_first_last", f"CREATE INDEX IF NOT EXISTS asset_first_last_idx ON {ASSET_TABLE} (first_year, first_quarter, last_year, last_quarter);")
build.run("analyze_asset", f"ANALYZE {ASSET_TABLE};")

✅ **[asset_build] idx_asset_first_last**: `ok` | `CREATE INDEX` | 0.0s

✅ **[asset_build] analyze_asset**: `ok` | `ANALYZE` | 0.1s

Empty DataFrame
Columns: []
Index: []

In [17]:
build.run("select_coverage", f"""
    WITH a AS (
    SELECT DISTINCT UPPER(TRIM(cusip)) AS cusip9,
                    LEFT(UPPER(TRIM(cusip)), 8) AS cusip8
    FROM clean_up_1.asset
),
h AS (
    SELECT DISTINCT UPPER(TRIM(cusip9)) AS cusip9,
                    LEFT(UPPER(TRIM(cusip9)), 8) AS cusip8
    FROM clean_up_1.holdings_clean
)
SELECT
    (SELECT COUNT(*) FROM h)                                         AS holdings_cusips,
    (SELECT COUNT(*) FROM a)                                         AS asset_cusips,
    (SELECT COUNT(*) FROM h WHERE cusip9 IN (SELECT cusip9 FROM a))  AS match_9,
    (SELECT COUNT(*) FROM h WHERE cusip8 IN (SELECT cusip8 FROM a))  AS match_8,
    (SELECT COUNT(*) FROM h
      WHERE cusip8 IN (SELECT cusip8 FROM a)
        AND cusip9 NOT IN (SELECT cusip9 FROM a))                    AS match_8_only,
    (SELECT COUNT(*) FROM h WHERE cusip8 NOT IN (SELECT cusip8 FROM a)) AS no_match;
""")

✅ **[asset_build] select_coverage**: `ok` | `SELECT 1` | rows: **1** | 15.3s

   holdings_cusips  asset_cusips  match_9  match_8  match_8_only  no_match
0            33610         40593    25807    33573          7766        37

   holdings_cusips  asset_cusips  match_9  match_8  match_8_only  no_match
0            33610         40593    25807    33573          7766        37

## 5. Asset checks

In [18]:
chk = p.stage("asset_checks")

chk.run("asset_summary", f"""
    SELECT count(*) AS assets,
           count(*) FILTER (WHERE quarters_missing > 0) AS with_gaps,
           min(first_year) AS first_year, max(last_year) AS last_year,
           round(avg(quarters_listed), 1) AS avg_quarters_listed
    FROM {ASSET_TABLE};
""", note="Previous test: 40,593 assets (2,551 with gaps)")

✅ **[asset_checks] asset_summary**: `ok` | `SELECT 1` | rows: **1** | 0.0s

> Previous test: 40,593 assets (2,551 with gaps)

   assets  with_gaps  first_year  last_year avg_quarters_listed
0   40593       2551        1996       2020                21.1

   assets  with_gaps  first_year  last_year avg_quarters_listed
0   40593       2551        1996       2020                21.1

### Gaps in listing

Most CUSIPs appear in one continuous run of lists. Gaps of 1–2 quarters are usually OCR misses; long gaps
are propably caused by rare appearence of given asset, changes in need to raport it or changes in one company (rebranding).

In [19]:
chk.run("asset_gap_distribution", f"""
    SELECT quarters_missing, count(*) AS assets
    FROM {ASSET_TABLE}
    GROUP BY quarters_missing
    ORDER BY quarters_missing
    LIMIT 30;
""", note="Previous test: 2,551 of 40,593 CUSIPs have at least one missing quarter")

✅ **[asset_checks] asset_gap_distribution**: `ok` | `SELECT 30` | rows: **30** | 0.0s

> Previous test: 2,551 of 40,593 CUSIPs have at least one missing quarter

    quarters_missing  assets
0                  0   38042
1                  1    1566
2                  2     209
3                  3     131
4                  4      66
5                  5      65
6                  6      52
7                  7      58
8                  8      28
9                  9      33
10                10      35
11                11      25
12                12      23
13                13      24
14                14      21
15                15      22
16                16      17
17                17      20
18                18      11
19                19      12
20                20      11
21                21      10
22                22       9
23                23       4
24                24       7
25                25       1
26                26       8
27                27       1
28                28       3
29                29       2

    quarters_missing  assets
0                  0   38042
1                  1    1566
2                  2     209
3                  3     131
4                  4      66
5                  5      65
6                  6      52
7                  7      58
8                  8      28
9                  9      33
10                10      35
11                11      25
12                12      23
13                13      24
14                14      21
15                15      22
16                16      17
17                17      20
18                18      11
19                19      12
20                20      11
21                21      10
22                22       9
23                23       4
24                24       7
25                25       1
26                26       8
27                27       1
28                28       3
29                29       2

In [20]:
chk.row_estimate(ASSET_TABLE, "asset")
chk.table_size(ASSET_TABLE, "asset")

✅ **[asset_checks] asset_count_exact**: `ok` | `SELECT 1` | rows: **1** | 0.0s

       n
0  40593

✅ **[asset_checks] asset_size**: `ok` | `SELECT 1` | rows: **1** | 0.0s

     total     heap  indexes
0  5304 kB  3304 kB  1968 kB

     total     heap  indexes
0  5304 kB  3304 kB  1968 kB

## 6. Run log analytics

Reads `steps.jsonl` from **all** runs in `logs/f13_securities/`.

In [21]:
logs = load_logs(LOG_ROOT)
steps_table(logs, p.run_id)

     seq               phase                         step status    statusmessage  rowcount  expected  diff  duration_s
116    1          connection      connection_check_server     ok             None       NaN       NaN   NaN       0.017
117    2          connection     connection_check_schemas     ok             None       NaN       NaN   NaN         NaN
118    3          connection      connection_check_tables     ok             None       NaN       NaN   NaN         NaN
119    4   securities_create        drop_securities_table     ok       DROP TABLE      -1.0       NaN   NaN       0.009
120    5   securities_create      create_securities_table     ok     CREATE TABLE      -1.0       NaN   NaN       0.010
121    6   securities_create         idx_securities_cusip     ok     CREATE INDEX      -1.0       NaN   NaN       0.004
122    7   securities_create  idx_securities_year_quarter     ok     CREATE INDEX      -1.0       NaN   NaN       0.003
123    8   securities_create     create_cusip_check_digit     ok  CREATE FUNCTION      -1.0       NaN   NaN       0.002
124    9   securities_create           check_digit_sanity     ok         SELECT 1       1.0       NaN   NaN       0.001
125   10     securities_load          preflight_csv_files     ok             None      99.0       NaN   NaN         NaN
126   11     securities_load               load_csv_files     ok             None  856547.0       NaN   NaN       7.395
127   12  securities_profile       securities_count_exact     ok         SELECT 1       1.0       NaN   NaN       0.025
128   13  securities_profile            securities_totals     ok         SELECT 1       1.0       NaN   NaN       1.995
129   14  securities_profile          securities_per_year     ok        SELECT 25      25.0       NaN   NaN       0.072
130   15  securities_profile        securities_duplicates     ok        SELECT 50      50.0       NaN   NaN       0.833
131   16  securities_profile       securities_check_digit     ok         SELECT 1       1.0       NaN   NaN       0.592
132   17  securities_profile           repair_check_digit     ok      UPDATE 1162    1162.0       NaN   NaN       0.180
133   18         asset_build           create_asset_table     ok     CREATE TABLE      -1.0       NaN   NaN       0.014
134   19         asset_build            insert_underlying     ok   INSERT 0 40593   40593.0   40593.0   0.0       8.545
135   20         asset_build         idx_asset_first_last     ok     CREATE INDEX      -1.0       NaN   NaN       0.023
136   21         asset_build                analyze_asset     ok          ANALYZE      -1.0       NaN   NaN       0.078
137   22         asset_build              select_coverage     ok         SELECT 1       1.0       NaN   NaN      15.334
138   23        asset_checks                asset_summary     ok         SELECT 1       1.0       NaN   NaN       0.007
139   24        asset_checks       asset_gap_distribution     ok        SELECT 30      30.0       NaN   NaN       0.004
140   25        asset_checks            asset_count_exact     ok         SELECT 1       1.0       NaN   NaN       0.002
141   26        asset_checks                   asset_size     ok         SELECT 1       1.0       NaN   NaN       0.002

In [22]:
# Row counts that differ from the previous run
expected_mismatches(logs, p.run_id)

Empty DataFrame
Columns: [seq, phase, step, status, statusmessage, rowcount, expected, diff, duration_s]
Index: []

In [23]:
phase_durations(logs, p.run_id)

                    seconds
phase
connection            0.017
securities_create     0.029
securities_load       7.395
securities_profile    3.697
asset_build          23.994
asset_checks          0.015

In [24]:
compare_runs(logs)

                                                      rowcount                                                                                      duration_s                                  \
run_id                                         20261008_212211 20261009_103639 20261009_110933 20261009_115233 20261009_120226 20261011_201543 20261008_212126 20261008_212211 20261009_103639
phase              step
connection         connection_check_server                 NaN             NaN             NaN             NaN             NaN             NaN           0.016           0.012             NaN
securities_create  drop_securities_table                  -1.0             NaN            -1.0             NaN            -1.0            -1.0             NaN           0.010             NaN
                   create_securities_table                -1.0             NaN            -1.0             NaN            -1.0            -1.0             NaN           0.009             NaN
                   idx_securities_cusip                   -1.0             NaN            -1.0             NaN            -1.0            -1.0             NaN           0.007             NaN
                   idx_securities_year_quarter            -1.0             NaN            -1.0             NaN            -1.0            -1.0             NaN           0.004             NaN
                   create_cusip_check_digit                NaN             NaN            -1.0             NaN            -1.0            -1.0             NaN             NaN             NaN
                   check_digit_sanity                      NaN             NaN             1.0             NaN             1.0             1.0             NaN             NaN             NaN
securities_load    preflight_csv_files                    99.0             NaN            99.0             NaN            99.0            99.0             NaN             NaN             NaN
                   load_csv_files                     856547.0             NaN        856547.0             NaN        856547.0        856547.0             NaN           8.208             NaN
securities_profile securities_count_exact                  1.0             NaN             1.0             NaN             1.0             1.0             NaN           0.020             NaN
                   securities_totals                       1.0             NaN             1.0             NaN             1.0             1.0             NaN           1.986             NaN
                   securities_per_year                    25.0             NaN            25.0             NaN            25.0            25.0             NaN           0.069             NaN
                   securities_duplicates                  50.0             NaN            50.0             NaN            50.0            50.0             NaN           0.433             NaN
                   securities_check_digit                  NaN             NaN             1.0             NaN             1.0             1.0             NaN             NaN             NaN
                   repair_check_digit                      NaN             NaN             0.0             NaN          1162.0          1162.0             NaN             NaN             NaN
asset_build        create_asset_table                      NaN            -1.0            -1.0            -1.0            -1.0            -1.0             NaN             NaN           0.016
                   insert_underlying                       NaN         42094.0         40593.0         40593.0         40593.0         40593.0             NaN             NaN           1.351
                   insert_options                          NaN         32315.0         30704.0         26623.0         26623.0             NaN             NaN             NaN           0.957
                   idx_asset_underlying_cusip              NaN            -1.0            -1.0            -1.0            -1.0             NaN             NaN             NaN           0.088
                   idx_asset_first_last                    NaN            -1.0            -1.0            -1.0            -1.0            -1.0             NaN             NaN           0.032
                   analyze_asset                           NaN            -1.0            -1.0            -1.0            -1.0            -1.0             NaN             NaN           0.122
                   select_coverage                         NaN             NaN             NaN             NaN             1.0             1.0             NaN             NaN             NaN
asset_checks       asset_by_type                           NaN             3.0             3.0             3.0             3.0             NaN             NaN             NaN           0.016
                   asset_gap_distribution                  NaN            30.0             NaN            30.0            30.0            30.0             NaN             NaN           0.007
                   asset_gap_examples                      NaN            30.0             NaN             NaN             NaN             NaN             NaN             NaN           0.007
                   asset_first_last_per_year               NaN            25.0             NaN             NaN             NaN             NaN             NaN             NaN           0.013
                   option_cusips_lost                      NaN             2.0             NaN             2.0             NaN             NaN             NaN             NaN           0.232
                   option_cusip_collisions                 NaN            30.0             NaN            30.0             NaN             NaN             NaN             NaN           0.112
                   excluded_invalid_cusips                 NaN             NaN           100.0           100.0             NaN             NaN             NaN             NaN             NaN
                   asset_count_exact                       NaN             NaN             NaN             1.0             1.0             1.0             NaN             NaN             NaN
                   asset_size                              NaN             NaN             NaN             1.0             1.0             1.0             NaN             NaN             NaN
                   asset_summary                           NaN             NaN             NaN             NaN             NaN             1.0             NaN             NaN             NaN


run_id                                         20261009_110933 20261009_115233 20261009_120226 20261011_201543
phase              step
connection         connection_check_server               0.017           0.019           0.012           0.017
securities_create  drop_securities_table                 0.011             NaN           0.011           0.009
                   create_securities_table               0.009             NaN           0.011           0.010
                   idx_securities_cusip                  0.006             NaN           0.004           0.004
                   idx_securities_year_quarter           0.005             NaN           0.003           0.003
                   create_cusip_check_digit              0.004             NaN           0.004           0.002
                   check_digit_sanity                    0.001             NaN           0.001           0.001
securities_load    preflight_csv_files                     NaN             NaN             NaN             NaN
                   load_csv_files                        6.292             NaN          10.762           7.395
securities_profile securities_count_exact                0.024             NaN           0.016           0.025
                   securities_totals                     1.957             NaN           1.991           1.995
                   securities_per_year                   0.065             NaN           0.064           0.072
                   securities_duplicates                 0.799             NaN           0.821           0.833
                   securities_check_digit                0.401             NaN           0.597           0.592
                   repair_check_digit                    0.121             NaN           0.159           0.180
asset_build        create_asset_table                    0.014           0.013           0.020           0.014
                   insert_underlying                     8.327           8.304           8.269           8.545
                   insert_options                        4.027           9.904           9.934             NaN
                   idx_asset_underlying_cusip            0.065           0.069           0.065             NaN
                   idx_asset_first_last                  0.039           0.031           0.032           0.023
                   analyze_asset                         0.115           0.119           0.120           0.078
                   select_coverage                         NaN             NaN          13.135          15.334
asset_checks       asset_by_type                         0.011           0.009           0.009             NaN
                   asset_gap_distribution                  NaN           0.007           0.006           0.004
                   asset_gap_examples                      NaN             NaN             NaN             NaN
                   asset_first_last_per_year               NaN             NaN             NaN             NaN
                   option_cusips_lost                      NaN           3.395             NaN             NaN
                   option_cusip_collisions                 NaN           2.183             NaN             NaN
                   excluded_invalid_cusips               2.540           2.528             NaN             NaN
                   asset_count_exact                       NaN           0.003           0.004           0.002
                   asset_size                              NaN           0.003           0.006           0.002
                   asset_summary                           NaN             NaN             NaN           0.007

In [25]:
p.close()

Run log: <THESIS_DIR>/src/Clean_solution/Database/Initialisation/pipelines/logs/f13_securities/20261011_201543/steps.jsonl